### PR TITLE
Fix input types resolver in generators

### LINKED ISSUE #310: When graphqlgen large schema will get stuck
## Description
In one of my projects, the datamodel has five hundred lines. My `schema.graphql` file imports the generated `prisma.graphql` schema file and has a hundred lines of Query and Mutation.

I get stuck when I run graphqlgen. Cpu and memory are slightly higher. I noticed a prompt for the `find prettier`, but I still didn't succeed after removing the prettier configuration.

My three computers have linux, mac, and windows systems, and they are not working properly. But the surprise is that my mac has been successful once, just once.

## Steps to reproduce
When `schema.graphql` too large.

My other small project run graphqlgen perfectly.

## Expected results
Graphqlgen work success.

## Actual results
Stucked. And console has no message.

## Versions
- graphqlgen: 0.4.0
- OS name and version: mac: 16G memory, mojava(darwin-x64). windows: win10 16G memory i7.
- Node: node-v10.8.0

### PR DESCRIPTION
**Pull request by zazido**
Fixes the potential unnecessary recursive function calls. Resolves #310 

For a type structure like this:

```
A
├── B ── C 
└── D ── C
```

`A` has child types `B` & `D`, `B` and `D` both have `C`.

When executing `deepResolveInputTypes(inputTypesMap, typeName, seen)` on `A -> B -> C -> D -> C`, C will still be marked as _unseen_ since `seen` is a new object on line:

https://github.com/prisma/graphqlgen/blob/f7a90f41aa297e70a1076698c9393096dab3ec12/packages/graphqlgen/src/generators/common.ts#L243  

Instead, we should use `seen` itself.

### TODO

- [x] update inline snapshot of `deepResolveInputTypes` test in `common.spec.ts`.

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
@zazido Thanks!

* It would be great if we can get unit test(s) coverage. I could help. My plan is to move to co-located unit test modules, e.g.: `/src/generators/common.spec.ts`. I could get the ball rolling via a commit to master that you then rebase. That you can focus just on the test and not the meta stuff around it.

* Also, it would be great if someone from #310 such as @Victorkangsh @vdiaz1130 @woss (anyone from that thread!) could checkout this branch and test if if fixes their issue.

🙏

**Comment by zazido** [comment]
@jasonkuhrt thanks for the great tool. I'm glad to help with 1 & 3 after your commit.

For those who want a quick fix from #310, go to `node_modules/graphqlgen/dist/generators/common.js` and change the function `deepResolveInputTypes` to: 

```javascript
function deepResolveInputTypes(inputTypesMap, typeName, seen) {
    if (seen === void 0) { seen = {}; }
    console.log(seen);
    var type = inputTypesMap[typeName];
    if (type) {
        var childTypes = type.fields
            .filter(function (t) { return t.type.isInput && !seen[t.type.name]; })
            .map(function (t) { return t.type.name; })
            .map(function (name) {
            seen[name] = true;
            return deepResolveInputTypes(inputTypesMap, name, seen);
        })
            .reduce(utils_1.flatten, []);
        return [typeName].concat(childTypes);
    }
    else {
        throw new Error("Input type " + typeName + " not found");
    }
}
```

and rerun `node_modules/.bin/gg` to see if there's any improvements. 

Looking forward to your feedback.

**Comment by jasonkuhrt** [comment]
I will try to address my own points but not sure when I will have it done. If you can do it before me all the better : )

File: packages/graphqlgen/src/generators/common.ts [hunk 1]
```diff
@@ -239,9 +239,10 @@ function deepResolveInputTypes(
     const childTypes = type.fields
       .filter(t => t.type.isInput && !seen[t.type.name])
       .map(t => t.type.name)
-      .map(name =>
-        deepResolveInputTypes(inputTypesMap, name, { ...seen, [name]: true }),
-      )
+      .map(name => {
+        seen[name] = true
```
Comment (jasonkuhrt) [inline packages/graphqlgen/src/generators/common.ts]: What is the intended effect of your change, given:

```ts
import * as _ from 'lodash'
const seen = {}
const name = 'bar'

const seenCopy = { ...seen, [name]: true }
seen[name] = true

assert(_.isEqual(seen, seenCopy))


```

?

Comment (jasonkuhrt) [reply packages/graphqlgen/src/generators/common.ts]: Ah, but by using mutation to share state across the recursion, we effectively guarantee that sibling traversal branches share their `seen` state...
